"use client";
import React from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api, API_BASE } from "@/lib/api";
import { notify } from "@/lib/toast";
import type { FindingActionKind, PrReviewComment, ReviewRecord, ReviewRunResponse, RunEvent, RunSummary } from "@devdigest/shared";
import { pullKeys, reviewKeys, runKeys } from "@/shared/api/query-keys";
export interface ActiveRun { run_id: string; agent_id: string | null; agent_name: string | null; ran_at: string | null; }
export function usePrActiveRuns(prId: string | null | undefined) { return useQuery({ queryKey: runKeys.active(prId), queryFn: () => api.get<ActiveRun[]>(`/pulls/${prId}/runs/active`), enabled: !!prId, refetchInterval: (q) => (q.state.data?.length ?? 0) > 0 ? 4000 : false }); }
export function usePrRuns(prId: string | null | undefined) { return useQuery({ queryKey: runKeys.history(prId), queryFn: () => api.get<RunSummary[]>(`/pulls/${prId}/runs`), enabled: !!prId, refetchInterval: (q) => (q.state.data ?? []).some((r) => r.status === "running") ? 4000 : false }); }
export function usePrReviews(prId: string | null | undefined) { return useQuery({ queryKey: reviewKeys.byPull(prId), queryFn: () => api.get<ReviewRecord[]>(`/pulls/${prId}/reviews`), enabled: !!prId }); }
export function useDeleteRun(prId: string | null | undefined) { const qc = useQueryClient(); return useMutation({ mutationFn: (runId: string) => api.del<{ ok: boolean }>(`/runs/${runId}`), onSuccess: () => { qc.invalidateQueries({ queryKey: runKeys.history(prId) }); qc.invalidateQueries({ queryKey: reviewKeys.byPull(prId) }); } }); }
export function useCancelRun() { return useMutation({ mutationFn: (runId: string) => api.post<{ ok: boolean }>(`/runs/${runId}/cancel`) }); }
export function useDeleteReview(prId: string | null | undefined) { const qc = useQueryClient(); return useMutation({ mutationFn: (reviewId: string) => api.del<{ ok: boolean }>(`/reviews/${reviewId}`), onSuccess: () => qc.invalidateQueries({ queryKey: reviewKeys.byPull(prId) }) }); }
export function usePrComments(prId: string | null | undefined) { return useQuery({ queryKey: reviewKeys.comments(prId), queryFn: () => api.get<PrReviewComment[]>(`/pulls/${prId}/comments`), enabled: !!prId }); }
export interface CreateCommentInput { path: string; line: number; side?: "LEFT" | "RIGHT"; body: string; in_reply_to?: number; }
export function useCreatePrComment(prId: string | null | undefined) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: CreateCommentInput) => api.post<PrReviewComment>(`/pulls/${prId}/comments`, input), onSuccess: () => qc.invalidateQueries({ queryKey: reviewKeys.comments(prId) }) }); }
export interface RunReviewInput { prId: string; repoId?: string; agentId?: string; all?: boolean; }
export function useRunReview() { const qc = useQueryClient(); return useMutation({ mutationFn: ({ prId, agentId, all }: RunReviewInput) => api.post<ReviewRunResponse>(`/pulls/${prId}/review`, { ...(agentId ? { agentId } : {}), ...(all ? { all } : {}) }), onSuccess: (_d, { prId, repoId }) => { qc.invalidateQueries({ queryKey: reviewKeys.byPull(prId) }); if (repoId) qc.invalidateQueries({ queryKey: pullKeys.list(repoId) }); } }); }
export function useFindingAction() { const qc = useQueryClient(); return useMutation({ mutationFn: ({ findingId, action, reply }: { findingId: string; action: FindingActionKind; reply?: string; prId?: string }) => api.post<{ finding: ReviewRecord["findings"][number]; memoryId?: string }>(`/findings/${findingId}/${action}`, reply ? { reply } : undefined), onSuccess: (_d, { prId }) => { if (prId) qc.invalidateQueries({ queryKey: reviewKeys.byPull(prId) }); } }); }
export function useRunEvents(runIds: string[]) { const [events, setEvents] = React.useState<RunEvent[]>([]); const [running, setRunning] = React.useState(false); const key = runIds.join(","); React.useEffect(() => { if (!runIds.length) return; setEvents([]); setRunning(true); const sources: EventSource[] = []; let open = runIds.length; for (const runId of runIds) { const es = new EventSource(`${API_BASE}/runs/${runId}/events`); const onMsg = (ev: MessageEvent) => { try { const parsed = JSON.parse(ev.data) as RunEvent; setEvents((prev) => [...prev, parsed]); if (parsed.kind === "error" && parsed.msg) notify.error(parsed.msg); } catch { /* keepalive */ } }; es.onmessage = onMsg; for (const kind of ["info", "tool", "result", "error"]) es.addEventListener(kind, onMsg as EventListener); es.onerror = () => { es.close(); open -= 1; if (open <= 0) setRunning(false); }; sources.push(es); } return () => { for (const es of sources) es.close(); setRunning(false); }; }, [key]); return { events, running }; }
export { reviewKeys, runKeys } from "@/shared/api/query-keys";
