"use client";
import React from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useTranslations } from "next-intl";
import { Skeleton, EmptyState, ErrorState, AutoTriggerStatus } from "@devdigest/ui";
import { AppShell } from "@/components/app-shell"; import { RepoNotFound } from "@/components/repo-not-found";
import { usePulls } from "@/features/pulls/api/hooks"; import { useRefreshRepo } from "@/features/repos/api/hooks"; import { useActiveRepo, useRepoNotFound } from "@/lib/repo-context"; import { ApiError } from "@/lib/api";
import { COLUMN_KEYS, RIGHT_ALIGNED_COLUMNS, SKELETON_ROWS } from "@/app/repos/[repoId]/pulls/constants"; import { s } from "@/app/repos/[repoId]/pulls/styles"; import { PRRow } from "@/app/repos/[repoId]/pulls/_components/PRRow"; import { FilterBar } from "@/app/repos/[repoId]/pulls/_components/FilterBar";
const OPEN_STATUSES = new Set(["needs_review", "reviewed", "stale"]);
export function PullsScreen({ repoId }: { repoId: string }) {
  const t = useTranslations("prReview"); const search = useSearchParams(); const router = useRouter(); const { activeRepo } = useActiveRepo(); const repoNotFound = useRepoNotFound(repoId); const { data: pulls, isLoading, isError, error, refetch } = usePulls(repoId); const refresh = useRefreshRepo(); const [query, setQuery] = React.useState(""); const [sort, setSort] = React.useState("newest"); const status = search.get("status") ?? "needs_review"; const q = query.trim().toLowerCase(); const filtered = (pulls ?? []).filter((p) => status === "all" || p.status === status).filter((p) => !q || p.title.toLowerCase().includes(q) || String(p.number).includes(q)).slice().sort((a, b) => { const ta = Date.parse(a.updated_at ?? "") || 0; const tb = Date.parse(b.updated_at ?? "") || 0; return sort === "oldest" ? ta - tb : tb - ta; });
  const setStatus = (value: string) => { const sp = new URLSearchParams(search.toString()); sp.set("status", value); router.replace(`/repos/${repoId}/pulls?${sp.toString()}`); }; const repoName = activeRepo?.full_name ?? repoId; const cloneFailed = Boolean(activeRepo && activeRepo.clone_path == null && activeRepo.clone_error); const openCount = (pulls ?? []).filter((p) => OPEN_STATUSES.has(p.status)).length; const needsReviewCount = (pulls ?? []).filter((p) => p.status === "needs_review").length;
  const crumb = [{ label: repoName, mono: true }, { label: t("list.breadcrumb") }]; if (repoNotFound) return <AppShell crumb={crumb}><RepoNotFound /></AppShell>;
  return <AppShell crumb={crumb}><div style={s.pageHeader}><div><h1 style={s.pageTitle}>{t("list.title")}</h1><p style={s.pageSubtitle}>{pulls ? t("list.summary", { open: openCount, needsReview: needsReviewCount }) : t("list.loading")}</p></div><div style={s.headerActions}><AutoTriggerStatus on={false} /></div></div><div style={s.tableCard}><FilterBar active={status} onActive={setStatus} query={query} onQuery={setQuery} sort={sort} onSort={setSort} onRefresh={() => refresh.mutate(repoId)} refreshing={refresh.isPending} /><div style={s.headRow}>{COLUMN_KEYS.map((key) => <div key={key} style={s.headCell(RIGHT_ALIGNED_COLUMNS.has(key))}>{t(`list.columns.${key}`)}</div>)}</div>{isLoading ? <div style={s.loadingStack}>{Array.from({ length: SKELETON_ROWS }).map((_, i) => <Skeleton key={i} height={28} />)}</div> : isError ? <ErrorState title={t("list.errorTitle")} body={error instanceof ApiError ? error.message : t("list.errorBody")} onRetry={() => refetch()} /> : filtered.length === 0 ? cloneFailed ? <ErrorState title={t("list.cloneErrorTitle")} body={activeRepo!.clone_error} onRetry={() => refresh.mutate(repoId)} /> : <EmptyState icon="GitPullRequest" title={t("list.emptyTitle")} body={status === "all" ? t("list.emptyAllBody") : t("list.emptyStatusBody", { status })} /> : filtered.map((pr) => <PRRow key={pr.number} pr={pr} repoId={repoId} />)}</div></AppShell>;
}
