import type { CSSProperties } from "react";

/** Co-located styles for BlastRadiusCard. */
export const s = {
  wrap: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  sectionTitle: { fontSize: 11, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--text-tertiary)" } satisfies CSSProperties,
  stats: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: "6px 16px", flex: "1 1 0", minWidth: 0 } satisfies CSSProperties,
  stat: { display: "inline-flex", alignItems: "center", gap: 6, fontSize: 13, color: "var(--text-tertiary)" } satisfies CSSProperties,
  statValue: { fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  statLabel: { color: "var(--text-secondary)" } satisfies CSSProperties,
  notice: {
    border: "1px solid var(--warning, #d29922)",
    borderRadius: 8,
    padding: "10px 12px",
    background: "var(--bg-hover)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  noticeText: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  noticeActions: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  noticeError: { fontSize: 12.5, color: "var(--danger, #f85149)" } satisfies CSSProperties,
  priorWrap: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  priorRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", fontSize: 13, padding: "4px 12px" } satisfies CSSProperties,
  priorLink: { fontFamily: "var(--font-mono, monospace)", fontSize: 13, fontWeight: 600, color: "var(--accent, var(--text-primary))" } satisfies CSSProperties,
  priorTitle: { color: "var(--text-secondary)", flex: "1 1 0", minWidth: 0 } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-tertiary)" } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: { borderRadius: 8, background: "var(--bg-hover)", padding: "8px 12px" } satisfies CSSProperties,
  rowHead: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  toggle: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    color: "var(--text-primary)",
    font: "inherit",
    textAlign: "left",
  } satisfies CSSProperties,
  symbol: { fontFamily: "var(--font-mono, monospace)", fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  symbolFile: { fontSize: 12, color: "var(--text-tertiary)", fontFamily: "var(--font-mono, monospace)" } satisfies CSSProperties,
  count: { marginLeft: "auto", fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  body: { display: "flex", flexDirection: "column", gap: 8, marginTop: 8, paddingLeft: 24 } satisfies CSSProperties,
  callers: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 3 } satisfies CSSProperties,
  caller: { fontSize: 13, display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center", color: "var(--text-tertiary)" } satisfies CSSProperties,
  callerName: { color: "var(--text-secondary)" } satisfies CSSProperties,
  link: { fontFamily: "var(--font-mono, monospace)", fontSize: 12.5, color: "var(--accent, #58a6ff)" } satisfies CSSProperties,
  location: { fontFamily: "var(--font-mono, monospace)", fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 6 } satisfies CSSProperties,
  statsRow: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12, flexWrap: "nowrap" } satisfies CSSProperties,
  toggleGroup: { display: "inline-flex", flexShrink: 0, border: "1px solid var(--border)", borderRadius: 8, padding: 2, gap: 2 } satisfies CSSProperties,
  toggleBtn: (active: boolean): CSSProperties => ({
    padding: "3px 12px",
    borderRadius: 6,
    fontSize: 12.5,
    fontWeight: 600,
    textTransform: "capitalize",
    cursor: "pointer",
    background: active ? "var(--bg-hover)" : "transparent",
    border: `1px solid ${active ? "var(--accent, #58a6ff)" : "transparent"}`,
    color: active ? "var(--text-primary)" : "var(--text-tertiary)",
  }),
  graphWrap: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  graphSvg: { width: "100%", height: "auto", maxHeight: 520, display: "block" } satisfies CSSProperties,
  legend: { display: "flex", gap: 16, flexWrap: "wrap", fontSize: 12, color: "var(--text-tertiary)" } satisfies CSSProperties,
  legendItem: { display: "inline-flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  legendDot: (color: string): CSSProperties => ({ width: 8, height: 8, borderRadius: 99, background: color, display: "inline-block" }),
  symbolIcon: { color: "var(--accent, #58a6ff)", display: "inline-flex" } satisfies CSSProperties,
} as const;

/** Endpoint chips are blue, cron chips amber, so the two kinds read apart (as in the design). */
export const chipTone = {
  endpoint: { color: "var(--accent, #58a6ff)", bg: "rgba(88, 166, 255, 0.12)" },
  cron: { color: "var(--warning, #d29922)", bg: "rgba(210, 153, 34, 0.14)" },
} as const;
