"use client";

import React from "react";
import { AppShell } from "../../components/app-shell";
import { Badge, Button, FormField, Markdown, SelectInput, Textarea, TextInput, Toggle } from "@devdigest/ui";
import { useCreateSkill, useImportSkill, useSkillImportPreview, useSkillVersions, useSkills, useUpdateSkill, type Skill } from "../../lib/hooks/skills";
import { readSkillFile } from "../../lib/skills-import";
import { buildSkillDiff } from "../../lib/skill-diff";

const types = ["rubric", "convention", "security", "custom"];

export default function SkillsPage() {
  const { data: skills = [], isLoading } = useSkills();
  const create = useCreateSkill();
  const importSkill = useImportSkill();
  const importPreview = useSkillImportPreview();
  const update = useUpdateSkill();
  const [query, setQuery] = React.useState("");
  const [selectedId, setSelectedId] = React.useState<string | null>(null);
  const [mode, setMode] = React.useState<"view" | "create" | "import">("view");
  const [tab, setTab] = React.useState("Config");
  const [draft, setDraft] = React.useState({ name: "", description: "", type: "custom", body: "" });
  const [importFilename, setImportFilename] = React.useState("");
  const [importError, setImportError] = React.useState<string | null>(null);
  const selected = skills.find((s) => s.id === selectedId) ?? null;
  const visible = skills.filter((s) => `${s.name} ${s.description}`.toLowerCase().includes(query.toLowerCase()));
  React.useEffect(() => { if (!selectedId && skills[0]) setSelectedId(skills[0].id); }, [selectedId, skills]);
  const save = () => { const done = (s: Skill) => { setSelectedId(s.id); setMode("view"); }; if (mode === "import") importSkill.mutate({ filename: importFilename, content: draft.body, name: draft.name, description: draft.description, type: draft.type as Skill["type"] }, { onSuccess: done }); else create.mutate({ ...draft, type: draft.type as Skill["type"], source: "manual", enabled: true }, { onSuccess: done }); };
  const importFile = async (file: File) => { setImportError(null); try { const content = await readSkillFile(file); const preview = await importPreview.mutateAsync({ filename: file.name, content }); setImportFilename(file.name); setDraft({ name: preview.name, description: preview.description, type: preview.type, body: preview.body }); setMode("import"); } catch (error) { setImportError(error instanceof Error ? error.message : "Could not read the skill file."); } };
  const saving = create.isPending || importSkill.isPending;
  const saveError = create.error ?? importSkill.error;
  return <AppShell crumb={[{ label: "Skills Lab" }, { label: "Skills" }]}><div style={{ display: "flex", height: "calc(100vh - 52px)" }}>
    <aside style={{ width: 320, borderRight: "1px solid var(--border)", padding: 16, overflow: "auto" }}><div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 14 }}><h1 style={{ flex: 1, fontSize: 18 }}>Skills</h1><Button kind="primary" size="sm" icon="Plus" onClick={() => { setDraft({ name: "", description: "", type: "custom", body: "" }); setMode("create"); }}>Add Skill</Button></div><TextInput value={query} onChange={setQuery} placeholder="Search skills…" />{isLoading ? <div style={{ padding: 20 }}>Loading…</div> : visible.map((skill) => { const selectSkill = () => { setSelectedId(skill.id); setTab("Config"); }; return <div key={skill.id} role="button" tabIndex={0} aria-pressed={selectedId === skill.id} onClick={(event) => { if ((event.target as HTMLElement).closest("button")) return; selectSkill(); }} onKeyDown={(event) => { if (event.currentTarget !== event.target) return; if (event.key === "Enter" || event.key === " ") { event.preventDefault(); selectSkill(); } }} style={{ marginTop: 10, padding: 14, border: `1px solid ${selectedId === skill.id ? "var(--accent)" : "var(--border)"}`, borderRadius: 8, cursor: "pointer" }}><div style={{ display: "flex", gap: 8 }}><strong style={{ flex: 1, fontFamily: "var(--font-mono)" }}>{skill.name}</strong><Toggle on={skill.enabled} onChange={(enabled) => update.mutate({ id: skill.id, patch: { enabled } })} size={15} /></div><div style={{ color: "var(--text-secondary)", fontSize: 12, margin: "8px 0" }}>{skill.description}</div><Badge color="var(--accent-text)" mono>{skill.type}</Badge><span style={{ color: "var(--text-muted)", fontSize: 12, marginLeft: 8 }}>v{skill.version} · {skill.source}</span></div>; })}<label style={{ display: "block", marginTop: 16, color: "var(--accent-text)", cursor: "pointer" }}>Import markdown or ZIP<input hidden type="file" accept=".md,.zip,text/markdown,application/zip" onChange={(e) => { const file = e.target.files?.[0]; if (file) void importFile(file); }} /></label>{importError && <p style={{ color: "var(--danger)", fontSize: 12 }}>{importError}</p>}</aside>
    <main style={{ flex: 1, minWidth: 0, overflow: "auto", padding: 28 }}>{mode !== "view" ? <Editor mode={mode} draft={draft} setDraft={setDraft} save={save} saving={saving} error={saveError} cancel={() => setMode("view")} /> : selected ? <Detail skill={selected} tab={tab} setTab={setTab} update={update} /> : <div style={{ padding: 60, color: "var(--text-secondary)" }}>Select a skill or create one.</div>}</main>
  </div></AppShell>;
}

function Editor({ mode, draft, setDraft, save, saving, error, cancel }: { mode: "create" | "import"; draft: { name: string; description: string; type: string; body: string }; setDraft: (v: typeof draft) => void; save: () => void; saving: boolean; error: unknown; cancel: () => void }) { const errorMessage = error ? (error instanceof Error ? error.message : String(error)) : null; return <div style={{ maxWidth: 760 }}><h2>{mode === "import" ? "Import Skill — Preview" : "Create Skill"}</h2><p style={{ color: "var(--text-secondary)" }}>{mode === "import" ? "Review the extracted markdown before saving. Archive files are treated as data only; executable entries are never run. Imported instructions will be appended to the agent prompt when enabled." : "Create a markdown-only skill configuration."}</p><FormField label="Name" required><TextInput value={draft.name} onChange={(v) => setDraft({ ...draft, name: v })} /></FormField><FormField label="Description" hint="Describe the skill interface directionally."><TextInput value={draft.description} onChange={(v) => setDraft({ ...draft, description: v })} /></FormField><FormField label="Type"><SelectInput value={draft.type} options={types} onChange={(v) => setDraft({ ...draft, type: v })} /></FormField><FormField label="Body (Markdown)"><Textarea value={draft.body} onChange={(v) => setDraft({ ...draft, body: v })} rows={18} mono /></FormField><Button kind="primary" onClick={save} disabled={!draft.name || !draft.body || saving}>{saving ? "Saving…" : "Save skill"}</Button>{" "}<Button kind="secondary" onClick={cancel}>Cancel</Button>{errorMessage && <p style={{ color: "var(--danger)", marginTop: 10 }}>Could not save skill. {errorMessage}</p>}</div>; }

function Detail({ skill, tab, setTab, update }: { skill: Skill; tab: string; setTab: (v: string) => void; update: ReturnType<typeof useUpdateSkill> }) {
  const { data: versions = [] } = useSkillVersions(skill.id);
  const [diffVersion, setDiffVersion] = React.useState<number | null>(null);
  const diffTarget = versions.find((v) => v.version === diffVersion) ?? null;
  const diffBase = diffTarget ? versions.find((v) => v.version === diffTarget.version - 1) ?? null : null;
  return <><div style={{ display: "flex", alignItems: "center", gap: 10 }}><h2 style={{ fontFamily: "var(--font-mono)" }}>{skill.name}</h2><Badge color="var(--accent-text)" mono>{skill.type}</Badge><Badge color="var(--text-secondary)" mono>v{skill.version}</Badge><label style={{ marginLeft: "auto" }}>Enabled <Toggle on={skill.enabled} onChange={(enabled) => update.mutate({ id: skill.id, patch: { enabled } })} /></label></div><p style={{ color: "var(--text-secondary)" }}>{skill.description}</p><nav style={{ borderBottom: "1px solid var(--border)", display: "flex", gap: 20 }}>{["Config", "Preview", "Versions", "Stats"].map((name) => <button key={name} onClick={() => setTab(name)} style={{ background: "none", color: tab === name ? "var(--accent-text)" : "var(--text-secondary)", border: 0, borderBottom: tab === name ? "2px solid var(--accent)" : "2px solid transparent", padding: "10px 0", cursor: "pointer" }}>{name}</button>)}</nav>{tab === "Preview" && <section style={{ marginTop: 22, padding: 22, border: "1px solid var(--border)", borderRadius: 8 }}><h3>Preview</h3><p style={{ color: "var(--text-secondary)" }}>Rendered as the reviewing agent receives it.</p><Markdown>{skill.body}</Markdown></section>}{tab === "Config" && <section style={{ marginTop: 22, maxWidth: 760 }}><SkillConfigEditor skill={skill} /></section>}{tab === "Stats" && <section style={{ marginTop: 22, display: "grid", gridTemplateColumns: "repeat(4, minmax(130px, 1fr))", gap: 12, maxWidth: 900 }}>{["Used by", "Pull frequency", "Accept rate", "Findings (30d)"].map((label) => <div key={label} style={{ padding: 18, border: "1px solid var(--border)", borderRadius: 8 }}><div style={{ color: "var(--text-secondary)", fontSize: 12, textTransform: "uppercase" }}>{label}</div><strong style={{ display: "block", fontSize: 25, marginTop: 10 }}>—</strong><span style={{ color: "var(--text-muted)", fontSize: 12 }}>No run metrics yet</span></div>)}</section>}{tab === "Versions" && <section style={{ marginTop: 22, maxWidth: 760 }}><h3>Version history · {versions.length} versions</h3><p style={{ color: "var(--text-secondary)" }}>Every save snapshots the body so runs remain reproducible.</p>{versions.map((v) => { const hasBase = versions.some((previous) => previous.version === v.version - 1); return <React.Fragment key={v.version}><div style={{ display: "flex", alignItems: "center", gap: 12, padding: 14, marginTop: 8, border: "1px solid var(--border)", borderRadius: 8 }}><strong>v{v.version}</strong><span style={{ color: "var(--text-secondary)" }}>{new Date(v.created_at).toLocaleDateString()}</span>{v.version === skill.version && <Badge color="var(--ok)" mono>Current</Badge>}<span style={{ flex: 1 }} />{hasBase && <Button kind="secondary" size="sm" onClick={() => setDiffVersion(diffVersion === v.version ? null : v.version)}>Diff</Button>}</div>{diffVersion === v.version && diffTarget && diffBase && <VersionDiff before={diffBase.body} after={diffTarget.body} />}</React.Fragment>; })}</section>}</>; }

function VersionDiff({ before, after }: { before: string; after: string }) { const rows = buildSkillDiff(before, after); return <div style={{ margin: "-1px 0 8px", padding: 12, border: "1px solid var(--border)", borderTop: 0, borderRadius: "0 0 8px 8px", background: "var(--bg-elevated)", fontFamily: "var(--font-mono)", fontSize: 12, whiteSpace: "pre-wrap" }}>{rows.map((item, index) => <div key={`${index}-${item.kind}`} style={{ color: item.kind === "added" ? "var(--ok)" : item.kind === "removed" ? "var(--danger)" : "var(--text-secondary)" }}>{item.kind === "added" ? "+ " : item.kind === "removed" ? "- " : "  "}{item.line}</div>)}</div>; }

function SkillConfigEditor({ skill }: { skill: Skill }) { const update = useUpdateSkill(); const [draft, setDraft] = React.useState({ name: skill.name, description: skill.description, type: skill.type, body: skill.body }); React.useEffect(() => setDraft({ name: skill.name, description: skill.description, type: skill.type, body: skill.body }), [skill.id, skill.version, skill.name, skill.description, skill.type, skill.body]); const dirty = draft.name !== skill.name || draft.description !== skill.description || draft.type !== skill.type || draft.body !== skill.body; return <><FormField label="Name" required><TextInput value={draft.name} onChange={(name) => setDraft({ ...draft, name })} /></FormField><FormField label="Description" hint="Write as a directive — what this skill instructs the agent to do."><TextInput value={draft.description} onChange={(description) => setDraft({ ...draft, description })} /></FormField><FormField label="Type"><SelectInput value={draft.type} options={types} onChange={(type) => setDraft({ ...draft, type: type as Skill["type"] })} /></FormField><FormField label={`Skill body (~${Math.max(1, Math.ceil(draft.body.length / 4))} tokens)`} hint="Markdown is appended to the agent prompt. Saving a changed body creates a new immutable version."><Textarea value={draft.body} onChange={(body) => setDraft({ ...draft, body })} rows={18} mono /></FormField><Button kind="primary" onClick={() => update.mutate({ id: skill.id, patch: draft })} disabled={!dirty || !draft.name || !draft.body || update.isPending}>{update.isPending ? "Saving…" : "Save changes"}</Button>{update.isError && <p style={{ color: "var(--danger)", marginTop: 10 }}>Could not save changes. {update.error instanceof Error ? update.error.message : "Try again."}</p>}</>; }
